import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "var(--outline-variant)",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "background": "var(--background)",
        "surface-dim": "var(--surface-dim)",
        "on-tertiary-fixed-variant": "#832600",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#001849",
        "on-secondary-container": "#5c647a",
        "primary-fixed": "#dae1ff",
        "tertiary-container": "#cc4204",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "var(--on-surface)",
        "surface-bright": "var(--surface)",
        "on-surface-variant": "var(--secondary)",
        "tertiary": "#a33200",
        "primary-container": "var(--primary-container)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed-dim": "#ffb59d",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "surface": "var(--surface)",
        "secondary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "surface-container-low": "var(--surface-container-low)",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "var(--secondary)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-tint": "#0054d6",
        "on-primary-fixed-variant": "#003fa4",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b3c5ff",
        "on-error-container": "#93000a",
        "secondary-container": "#dae2fd",
        "on-tertiary-fixed": "#390c00",
        "inverse-surface": "#213145",
        "on-tertiary-container": "#fff6f4",
        "inverse-primary": "#b3c5ff",
        "on-surface": "var(--on-surface)",
        "surface-container-highest": "#d3e4fe",
        "surface-container": "var(--surface-container)",
        "primary": "var(--primary)",
        "outline": "var(--outline)",
        "on-primary": "var(--on-primary)",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbd0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        md: "16px",
        base: "4px",
        xs: "4px",
        lg: "24px",
        "sidebar-width": "260px",
        xl: "40px",
        gutter: "16px",
        sm: "8px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Geist", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "mono-sm": ["Geist", "monospace"],
        sans: ["Inter", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
      },
      keyframes: {
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
      },
      animation: {
        blob: "blob 7s infinite alternate",
      },
    },
  },
  plugins: [],
};
export default config;
